#!/bin/sh

if test -z "$NDK" ; then
	export NDK=/usr/local/app/Android/SDK/ndk-bundle
fi
$NDK/ndk-build $* || exit $?

test -n "$*" && exit 0

ANDRAW=android/app/src/main/res/raw
for afrd in libs/*/afrd ; do
	arch=$(basename $(dirname $afrd) | tr '-' '_')
	cp $afrd $ANDRAW/afrd_$arch
done

VERSION=`sed main.c -ne '/const char \*g_version/{' -e 's/^.*= *"//' -e 's/".*$//' -e p -e '}'`
SUFFIX=`sed main.c -ne '/const char \*g_ver_sfx/{' -e 's/^.*= *"//' -e 's/".*$//' -e p -e '}'`
BUILD=android/app/build.gradle
sed -e "s/\( *versionName *'\).*\('\)/\1$VERSION\2/" \
    -e "s/\( *versionNameSuffix *'\).*\('\)/\1$SUFFIX\2/" \
	"${BUILD}" > "${BUILD}~"
if ! cmp -s "${BUILD}~" "${BUILD}" ; then
	mv -f "${BUILD}~" "${BUILD}"
	echo "Updated Android version number to $VERSION$SUFFIX"
else
	rm -f "${BUILD}~"
fi

cp config/afrd-android7-.ini android/app/src/main/res/raw/afrd_7.ini
cp config/afrd-android8+.ini android/app/src/main/res/raw/afrd_8.ini
cp ChangeLog-en.txt android/app/src/main/res/raw/changelog.txt
cp ChangeLog-ru.txt android/app/src/main/res/raw-ru/changelog.txt
cp FAQ-en.txt android/app/src/main/res/raw/faq.txt
cp FAQ-ru.txt android/app/src/main/res/raw-ru/faq.txt
