#!/sbin/sh

ui_print "--<< Auto FrameRate Daemon installer >>--"

mnt system

INITD=/system/etc/init.d
test -d $INITD || INITD=/system/su.d
if ! test -d $INITD ; then
	ui_print "Your system is not configured for init.d support!"
	ui_print "Please configure your system before installing afrd!"
	ui_print "FAILING INSTALLATION"
	exit 1
fi

if test -f /sys/class/switch/hdmi/cable.0/state ; then
	ui_print "Kernel version 4.x detected, supposing Android 8 and up"
	package_extract_file config/afrd-android8+.ini /system/etc/afrd.ini
elif test -f /sys/class/switch/hdmi/state ; then
	ui_print "Kernel version 3.x detected, supposing Android 6 or 7"
	package_extract_file config/afrd-android7-.ini /system/etc/afrd.ini
else
	ui_print "Unknown kernel type, failing installation"
	exit 1
fi

if test -f /system/xbin/afrd ; then
	ui_print "UNINSTALLING existing afrd"
	rm -f /system/xbin/afrd /system/etc/afrd.ini $INITD/50-afrd
else
	ARCH=`getprop ro.product.cpu.abi`
	ui_print "INSTALLING binaries for arch $ARCH"

	ui_print "INSTALLING autostart script to $INITD"
	package_extract_file 50-afrd $INITD
	package_extract_file $ARCH/afrd /system/xbin

	ui_print "SETTING UP access rights, modes and contexts..."
	package_extract_file afrd.perm $TMP
	perm $TMP/afrd.perm
	set_perm 0 0 0755 u:object_r:system_file:s0 $INITD/50-afrd
fi

ui_print "Done"
