#!/sbin/sh

ui_print "Installing --<< Auto FrameRate Daemon >>--"

mnt system

if ! test -d /system/etc/init.d ; then
	ui_print "Your system is not configured for init.d support!"
	ui_print "Please configure your system before installing afrd!"
	exit 1
fi

# Let's suppose kernel >= 4 means Android 8 and up
KVER=`uname -r | cut -c1`
if test "$KVER" == "3" ; then
	echo "Kernel version 3.x detected, supposing android 6 or 7"
	package_extract_file afrd-android7-.ini /system/etc/afrd.ini
else
	echo "Kernel version $KVER.x detected, supposing android 8 and up"
	package_extract_file afrd-android8+.ini /system/etc/afrd.ini
fi

ARCH=`getprop ro.product.cpu.abi`
ui_print "Installing binaries for arch $ARCH"

package_extract_file 50-afrd /system/etc/init.d
package_extract_file $ARC/afrd /system/xbin

ui_print "Setting up access rights, modes and contexts..."
package_extract_file afrd.perm $TMP
perm $TMP/afrd.perm

ui_print "Done"
